loopSeconds: 3
auth:
  httpsOnly: true
  proxied: true
#  ipWhitelisting:
#    whitelistExpirySeconds: 86400
#    secretKey: YOURTOKEN
#  jwt:
#    userName: joe
#    password: bloggs
#    secret: CHANGEME
#    secondFactorSecret: YOURTOKEN
#    expirationMinutes: 1440
#  okta:
#    baseUrl: SEE
#    issuer: THE
#    clientId: README
database:
  mongoClientURI: mongodb://jsmith:some-initial-password@localhost:27017/yourdb # Your mongoDB connection details.
  lockSeconds: 10
# telegram:
#   botToken: YOU
#   chatId: REALLYWANTTHIS
mq:
  clientURI: amqp://localhost
exchanges:
  gdax-sandbox:
    apiKey: 
    secretKey: 
    passphrase: 
  gdax:
    apiKey: 
    secretKey: 
    passphrase: 
  binance:
    apiKey: 
    secretKey:
  kucoin:
    apiKey: 
    secretKey: 
  cryptopia:
    apiKey: 
    secretKey: 
  bitfinex:
    apiKey: 
    secretKey: 
jerseyClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  connectionRequestTimeout: 5000ms
server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  connector:
    type: http
    port: 8080
  maxThreads: 16
logging:
  loggers:
    "com.gruelbox.orko": INFO
    "si.mazi.rescu": ERROR