loopSeconds: ${LOOP_SECONDS}
auth:
  httpsOnly: true
  proxied: ${PROXIED}
  whitelistExpirySeconds: ${WHITELIST_EXPIRY_SECONDS}
  secretKey: ${AUTH_TOKEN}
  okta:
    baseUrl: ${OKTA_BASEURL}
    issuer: ${OKTA_ISSUER}
    clientId: ${OKTA_CLIENTID}
telegram:
  botToken: ${TELEGRAM_BOT_TOKEN}
  chatId: ${TELEGRAM_CHAT_ID}
database:
  mongoClientURI: ${MONGODB_URI}
  lockSeconds: ${LOCK_SECONDS}
exchanges:
  gdax-sandbox:
    apiKey: ${GDAX_SANDBOX_API_KEY}
    secretKey: ${GDAX_SANDBOX_SECRET}
    passphrase: ${GDAX_SANDBOX_PASSPHRASE}
  gdax:
    apiKey: ${GDAX_API_KEY}
    secretKey: ${GDAX_SECRET}
    passphrase: ${GDAX_PASSPHRASE}
  binance:
    apiKey: ${BINANCE_API_KEY}
    secretKey: ${BINANCE_SECRET}
  kucoin:
    apiKey: ${KUCOIN_API_KEY}
    secretKey: ${KUCOIN_SECRET}
  bitfinex:
    apiKey: ${BITFINEX_API_KEY}
    secretKey: ${BITFINEX_SECRET}
  bittrex:
    apiKey: ${BITTREX_API_KEY}
    secretKey: ${BITTREX_SECRET}
  cryptopia:
    apiKey: ${CRYPTOPIA_API_KEY}
    secretKey: ${CRYPTOPIA_SECRET}
server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  connector:
    type: http
    port: 8080
  requestLog:
    appenders: []
  maxThreads: 16
jerseyClient:
  timeout: 15000ms
  connectionTimeout: 15000ms
  connectionRequestTimeout: 15000ms
logging: 
  loggers:
    "com.grahamcrockford.orko": ${LOG_LEVEL}
    "info.bitrich.xchangestream.service.netty": ${LOG_LEVEL}
    "info.bitrich.xchangestream.binance": ${LOG_LEVEL}
    "info.bitrich.xchangestream.gdax": ${LOG_LEVEL}
    "si.mazi.rescu": ERROR