loopSeconds: ${LOOP_SECONDS:-15}
scriptSigningKey: ${SCRIPT_SIGNING_KEY}
auth:
  httpsOnly: true
  proxied: true
  ipWhitelisting:
    whitelistExpirySeconds: ${WHITELIST_EXPIRY_SECONDS:-86400}
    secretKey: ${AUTH_TOKEN:-}
  jwt:
    userName: ${SIMPLE_AUTH_USERNAME:-}
    password: ${SIMPLE_AUTH_PASSWORD:-}
    passwordSalt: ${SIMPLE_AUTH_SALT:-}
    secret: ${SIMPLE_AUTH_SECRET:-}
    secondFactorSecret: ${SIMPLE_AUTH_SECOND_FACTOR:-}
    expirationMinutes: ${SIMPLE_AUTH_TOKEN_EXPIRY_MINUTES:-1440}
telegram:
  botToken: ${TELEGRAM_BOT_TOKEN:-}
  chatId: ${TELEGRAM_CHAT_ID:-}
database:
  connectionString: ${JAWSDB_URL}?rewriteBatchedStatements=true&useJDBCCompliantTimezoneShift=true
  lockSeconds: ${LOCK_SECONDS:-45}
exchanges:
  simulated:
    apiKey: ${SIMULATED_API_KEY:-}
  gdax:
    apiKey: ${GDAX_API_KEY:-}
    secretKey: ${GDAX_SECRET:-}
    passphrase: ${GDAX_PASSPHRASE:-}
    sandbox: ${GDAX_SANDBOX:-false}
    loadRemoteData: ${GDAX_REMOTE_META:-true}
  binance:
    apiKey: ${BINANCE_API_KEY:-}
    secretKey: ${BINANCE_SECRET:-}
    loadRemoteData: ${BINANCE_REMOTE_META:-true}
  kucoin:
    apiKey: ${KUCOIN_API_KEY:-}
    secretKey: ${KUCOIN_SECRET:-}
    passphrase: ${KUCOIN_PASSPHRASE:-}
    sandbox: ${KUCOIN_SANDBOX:-false}
    loadRemoteData: ${KUCOIN_REMOTE_META:-true}
  bitfinex:
    apiKey: ${BITFINEX_API_KEY:-}
    secretKey: ${BITFINEX_SECRET:-}
    loadRemoteData: ${BITFINEX_REMOTE_META:-true}
  bitmex:
    apiKey: ${BITMEX_API_KEY:-}
    secretKey: ${BITMEX_SECRET:-}
    loadRemoteData: ${BITMEX_REMOTE_META:-true}
  kraken:
    apiKey: ${KRAKEN_API_KEY:-}
    secretKey: ${KRAKEN_SECRET:-}
    loadRemoteData: ${KRAKEN_REMOTE_META:-true}
  bittrex:
    apiKey: ${BITTREX_API_KEY:-}
    secretKey: ${BITTREX_SECRET:-}
    loadRemoteData: ${BITTREX_REMOTE_META:-true}
server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  connector:
    type: http
    port: 8080
  requestLog:
    appenders: []
  maxThreads: 16
jerseyClient:
  timeout: 15000ms
  connectionTimeout: 15000ms
  connectionRequestTimeout: 15000ms
logging:
  loggers:
    "com.gruelbox.orko": ${LOG_LEVEL:-INFO}
    "info.bitrich.xchangestream.service.netty": ${LOG_LEVEL:-INFO}
    "info.bitrich.xchangestream.binance": ${LOG_LEVEL:-INFO}
    "info.bitrich.xchangestream.gdax": ${LOG_LEVEL:-INFO}
    "info.bitrich.xchangestream.binance.BinanceUserDataStreamingService": ${LOG_LEVEL_BINANCE_RAW_USER:-INFO}
    "si.mazi.rescu": ERROR
